# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

# Note: jekyll-paginate is deprecated
gems: [jekyll-paginate]
paginate: 10 # pagination basted on number of posts

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

